chart_dev_mode: false

ingress:
  tls_resolver: letsencrypt

hpa:
  enabled: false

hostname: e2e-k8s.opencrvs.dev
elasticsearch:
  auth_mode: auto
  port: 9200
  host: elasticsearch.opencrvs-deps-e2e.svc.cluster.local
  auth_users:
    - SEARCH:{{STACK}}_elastic
    - KIBANA_USER:{{STACK}}_kibana
    - KIBANA_SYSTEM:{{STACK}}_kibana_system
    - METRICBEAT:{{STACK}}_beats_system
    - APM:{{STACK}}_apm_system

minio:
  auth_mode: use_secret
  host: minio-0.minio.opencrvs-deps-e2e.svc.cluster.local
  external_url: minio.e2e-k8s.opencrvs.dev

mongodb:
  auth_mode: auto
  host: mongodb-0.mongodb.opencrvs-deps-e2e.svc.cluster.local
  databases:
    - prefix: USER_MGNT
      db: {{STACK}}--user-mgnt
      user: {{STACK}}--user-mgnt
    - prefix: HEARTH
      db: {{STACK}}--hearth-dev
      user: {{STACK}}--hearth
      roles: "[{ role: 'readWrite', db: '{{STACK}}--hearth' }, { role: 'readWrite', db: 'performance' }, { role: 'readWrite', db: '{{STACK}}--hearth-dev' }]"
    - prefix: PERFORMANCE
      db: {{STACK}}--performance
      user: {{STACK}}--performance
    - prefix: EVENTS
      db: {{STACK}}--events
      user: {{STACK}}--events
      roles: "[{ role: 'readWrite', db: '{{STACK}}--events' }, {role: 'read', db: '{{STACK}}--user-mgnt'}]"
redis:
  auth_mode: use_secret
  host: redis-0.redis.opencrvs-deps-e2e.svc.cluster.local


postgres:
  auth_mode: auto
  host: postgres-0.postgres.opencrvs-deps-e2e.svc.cluster.local
  events_db: {{STACK_SANITIZED}}__events
  events_migrator: {{STACK_SANITIZED}}_migrator
  events_app: {{STACK_SANITIZED}}_app
  events_analytics: {{STACK_SANITIZED}}_analytics

resources:
  memoryRequest: "128Mi"
  cpuRequest: "150m"
  memoryLimit: "2Gi"
  cpuLimit: "4"

auth:
  env:
    TWO_FA_ENABLED: "false"

dashboards:
  enabled: false

gateway:
  env:
    MINIO_BUCKET: {{STACK}}--ocrvs
    DISABLE_RATE_LIMIT: "true"
  resources:
    memoryRequest: "512Mi"
    cpuRequest: "200m"
    memoryLimit: "2Gi"
    cpuLimit: "1"

config:
  resources:
    memoryRequest: "1Gi"
    cpuRequest: "200m"
    memoryLimit: "2Gi"
    cpuLimit: "1"

client:
  env:
   CONTENT_SECURITY_POLICY_WILDCARD: "*.e2e-k8s.opencrvs.dev"
countryconfig:
  image:
    name: opencrvs/opencrvs-testland
    tag: develop
  env:
    OPENID_PROVIDER_CLAIMS: name,family_name,given_name,middle_name,birthdate,address
    OPENID_PROVIDER_CLIENT_ID: mock-client_id
    # FIXME: In general these values should be passed externally using `--set key=value`
    ESIGNET_REDIRECT_URL: https://esignet-mock.{{STACK}}.e2e-k8s.opencrvs.dev/authorize
    MOSIP_API_USERINFO_URL: https://mosip-api.{{STACK}}.e2e-k8s.opencrvs.dev/esignet/get-oidp-user-info
    # Country config passes minio details to client. 'ocrvs' is hardcoded. To get files working in E2E, countryconfig needs to be configured with the same bucket name as gateway, migration and documents.
    # E2E prefix intention is to communicate, that this is only for E2E testing and not for production.
    E2E_MINIO_BUCKET: {{STACK}}--ocrvs
    # In E2E environment, minio is shared between all services. STACK is omitted from the path. Differentiation is done by bucket name.
    E2E_MINIO_BASE_URL: https://minio.e2e-k8s.opencrvs.dev
    REFERENCE_DATA_DATABASE_URL: postgres://{{STACK_SANITIZED}}_ref_data:{{STACK_SANITIZED}}_ref_data_password@postgres-0.postgres.opencrvs-deps-e2e.svc.cluster.local:5432/{{STACK_SANITIZED}}__events

events:
  env:
    ES_INDEX_PREFIX: events_{{STACK}}
    ES_REINDEXING_STATUS_INDEX: reindexing_status_{{STACK}}
    DEFAULT_USER_PASSWORD: "test"
    TWO_FA_ENABLED: "false"
  resources:
    memoryRequest: "1Gi"
    cpuRequest: "1"
    memoryLimit: "2Gi"

search:
  env:
    OPENCRVS_INDEX_NAME: ocrvs--{{STACK}}

documents:
  env:
    MINIO_BUCKET: {{STACK}}--ocrvs

data_migration:
  env:
    MINIO_BUCKET: {{STACK}}--ocrvs
    ELASTICSEARCH_INDEX_NAME: ocrvs--{{STACK}}

postgres_on_deploy:
  env:
    TARGET_DB: {{STACK_SANITIZED}}__events
    REFERENCE_DATA_POSTGRES_USER: {{STACK_SANITIZED}}_ref_data
    REFERENCE_DATA_POSTGRES_PASSWORD: {{STACK_SANITIZED}}_ref_data_password
    REFERENCE_DATA_EDITOR_USER: {{STACK_SANITIZED}}_ref_editor
    REFERENCE_DATA_EDITOR_PASSWORD: {{STACK_SANITIZED}}_ref_editor_password

data_seed:
  enabled: false
  env:
    ACTIVATE_USERS: "true"

data_cleanup:
  env:
    MINIO_BUCKET: {{STACK}}--ocrvs
    ES_INDEX_PREFIX: events_{{STACK}}
    ELASTICSEARCH_INDEX_NAME: ocrvs--{{STACK}}
    ES_REINDEXING_STATUS_INDEX: reindexing_status_{{STACK}}

env:
  APN_SERVICE_URL: "http://apm-server.opencrvs-deps-e2e.svc.cluster.local:8200"
  APN_ENVIRONMENT: {{STACK}}