chart_dev_mode: false
hostname: e2e-k8s.opencrvs.dev

storage_type: host_path

ingress:
  tls_resolver: letsencrypt

minio:
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false

mongodb:
  use_default_credentials: false

postgres:
  image: chumaky/postgres_mongo_fdw:17.6_fdw5.5.2
  use_default_credentials: false

monitoring:
  enabled: true

redis:
  auth_mode: acl


node_selector:
 role: data1

monitoring:
  enabled: true

filebeat:
  image: ghcr.io/opencrvs/filebeat:8.16.4
  custom_ilm_configmap: filebeat-ilm-config-e2e

metricbeat:
  image: ghcr.io/opencrvs/metricbeat:8.16.4
  custom_ilm_configmap: metricbeat-ilm-config-e2e

apm_server:
  custom_config_configmap: apm-server-config-e2e