ingress:
  tls_resolver: letsencrypt
  ssl_enabled: true

mosip_api:
  host_data_path: /data/sqlite_{{STACK_SANITIZED}}
  env:
    OPENCRVS_AUTH_URL: http://auth.opencrvs-{{STACK}}.svc.cluster.local:4040
