name: "10. Cleanup Old E2E Namespaces"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # every hour; adjust as needed

jobs:
  discover_cleanup:
    name: List namespaces to cleanup
    runs-on: self-hosted
    outputs:
      namespaces: ${{ steps.discover_ns.outputs.namespaces }}
    steps:
      - name: Cleanup old namespaces except keep_namespace=true
        id: discover_ns
        env:
          # Set how old namespaces must be to be purged (in seconds)
          AGE_THRESHOLD: 10800  # Default 3 hours
        run: |
          THRESHOLD=${AGE_THRESHOLD}
          NOW=$(date +%s)
          echo "⚠️ Deleting namespaces older than $((THRESHOLD/3600)) hours unless keep_namespace=true:"
          NAMESPACES="$(kubectl get ns -o json | jq -r '.items[] | select(.metadata.labels.keep_namespace != "true") | .metadata.name' | grep opencrvs | grep -v 'opencrvs-deps-e2e')" || NAMESPACES=""
          KEEP_NAMESPACES=$(kubectl get ns -o json | jq -r '.items[] | select(.metadata.labels.keep_namespace == "true") | .metadata.name')

          NAMESPACES_TO_CLEANUP=()
          for ns in $NAMESPACES; do
            UPDATED_AT=$(kubectl get ns "$ns" -o jsonpath='{.metadata.labels.updated_at}')
            AGE=$((NOW - UPDATED_AT))
            if [ -z "$UPDATED_AT" ]; then
              echo " - ℹ️ Skipping namespace $ns, no update_at label"
            elif [ "$AGE" -ge "$THRESHOLD" ]; then
              echo " - 🧹 Adding namespace $ns to cleanup list"
              NAMESPACES_TO_CLEANUP+=("$ns")
            else
              echo " - 🕒 Skipping namespace $ns (not old enough: $((AGE/3600))h $(( (AGE%3600)/60 ))m)"
            fi
          done
          namespaces_json=$(printf '%s\n' "${NAMESPACES_TO_CLEANUP[@]}" | jq -R -s -c 'split("\n")[:-1]')
          echo "namespaces=$namespaces_json" >> $GITHUB_OUTPUT
          echo "🔒 Following namespaces will be skipped, label keep_namespace=true:"
          printf '\t- %s\n' $KEEP_NAMESPACES
          echo "🗑️ Following namespaces will be removed:"
          printf '\t- %s\n' "${NAMESPACES_TO_CLEANUP[@]}"
  cleanup:
    needs: discover_cleanup
    runs-on: self-hosted
    env:
      namespace: ${{ matrix.namespace }}
    if: ${{ needs.discover_cleanup.outputs.namespaces != '[""]' && needs.discover_cleanup.outputs.namespaces != '[]' && needs.discover_cleanup.outputs.namespaces != '' }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        namespace: ${{ fromJson(needs.discover_cleanup.outputs.namespaces) }}
    name: Remove ${{ matrix.namespace }}
    steps:
        - name: Checkout repo
          uses: actions/checkout@v6
        - name: Get helm release values and Quote specific fields that are commonly numeric
          id: get-values
          run: |
            helm get values opencrvs -n $namespace -ojson > /tmp/${namespace}.json || FAILED=true
            if [ "$FAILED" = true ]; then
              echo "⚠️ Warning: No OpenCRVS Helm release found in namespace ${namespace}"
              ENV=${namespace/opencrvs-/}
              TEMPLATE_VALUES_FILE=/tmp/${namespace}.yaml
              VALUES_FILE=/tmp/${namespace}.json
              sed -e "s#{{STACK_SANITIZED}}#${ENV//-/_}#g" \
                 -e "s#{{STACK}}#${ENV}#g" k8s-env/opencrvs/values.yaml | yq -ojson > ${TEMPLATE_VALUES_FILE}
              if yq --version 2>&1 | grep -qi 'mikefarah'; then
                yq -o=json '.' "${TEMPLATE_VALUES_FILE}" > "${VALUES_FILE}"
              else
                yq '.' "${TEMPLATE_VALUES_FILE}" > "${VALUES_FILE}"
              fi
            fi
        # FIXME: utilities.image.tag remove after v2.1.0 release
        - name: Cleanup environment
          run: |
            kubectl delete job -n ${namespace} --ignore-not-found=true data-cleanup
            helm template -f /tmp/${namespace}.json \
                --set data_cleanup.enabled=true \
                --set data_cleanup.env.make_bucket=false \
                --set utilities.image.tag=35b1e0f \
                --namespace ${namespace} \
                -s templates/data-cleanup-job.yaml \
                oci://ghcr.io/opencrvs/opencrvs-services:v2.1.0 | kubectl apply -n ${namespace} --wait=true -f -
            sleep 30;
            kubectl logs job/data-cleanup -f --all-containers=true -n ${namespace} || true
            kubectl wait --for=condition=complete job/data-cleanup -n ${namespace} --timeout=600s;
        - name: Uninstall helm release
          run: helm uninstall opencrvs -n ${namespace} || echo "Helm release is not installed"
        - name: Delete namespace ${namespace}
          if: always()
          run: kubectl delete ns ${namespace}
