name: 03. Deploy Dependencies
run-name: Deploy Dependencies on ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "e2e"
        type: choice
        options:
          - "e2e"

env:
  DEPENDENCIES_CHART_VERSION: "v2.0.0"
  TRAEFIK_CHART_VERSION: "39.0.0"

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    env:
      ENV: ${{ inputs.environment }}
      GITHUB_ACTOR: ${{ github.actor }}
      SENDER_EMAIL_ADDRESS: ${{ secrets.SENDER_EMAIL_ADDRESS }}
      ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Install Traefik
        run: |
          kubectl scale deployment traefik --replicas=0 --namespace traefik || true
          helm upgrade --install traefik oci://ghcr.io/traefik/helm/traefik:${TRAEFIK_CHART_VERSION} \
            --namespace traefik \
            --create-namespace \
            -f https://raw.githubusercontent.com/opencrvs/e2e/${{ github.ref_name }}/k8s-env/traefik/values.yaml
          kubectl scale deployment traefik --replicas=1 --namespace traefik
      - name: Apply configmaps
        # Normally helm creates namespace. But since we want to apply configmaps before helm, we need to ensure the namespace is present.
        run: |
          kubectl create namespace opencrvs-deps-e2e --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s-env/dependencies/configmaps/
      - name: Install OpenCRVS dependencies
        id: deploy
        run: |
          stern -n "opencrvs-deps-${ENV}" \
            --since 1s \
            --tail 0 \
            --exclude 'kube-probe' \
            --exclude '"level":(30|info)' \
            --template '{{.PodName}}/{{.ContainerName}} | {{.Message}}{{"\n"}}' \
            . &
          STERN_PID=$!
          helm upgrade --install opencrvs-deps oci://ghcr.io/opencrvs/opencrvs-dependencies-chart:${DEPENDENCIES_CHART_VERSION} \
            --namespace "opencrvs-deps-e2e" \
            -f https://raw.githubusercontent.com/opencrvs/e2e/${{ github.ref_name }}/k8s-env/dependencies/values.yaml \
            --create-namespace \
            --timeout 15m \
            --atomic; STATUS=$?;

          kill $STERN_PID 2>/dev/null || true
          exit $STATUS

