name: Deploy & run E2E
run-name: 'E2E by ${{ github.event.client_payload.actor || github.actor }} to ${{ github.event.client_payload.stack || github.event.inputs.stack }}. (core: ${{ github.event.client_payload.core-image-tag || github.event.inputs.core-image-tag }}, farajaland: ${{ github.event.client_payload.countryconfig-image-tag || github.event.inputs.countryconfig-image-tag }})'
on:
  repository_dispatch:
    types: [run_e2e]
  workflow_dispatch:
    inputs:
      core-image-tag:
        description: Core image tag
        required: true
        default: 'v1.8.0'
      countryconfig-image-tag:
        description: Your Country Config DockerHub image tag
        required: true
        default: 'v1.8.0'
      stack:
        type: string
        description: Stack name
        required: true
      keep-e2e:
        description: Keep environment after run
        required: false
        default: false
        type: boolean
      branch:
        description: e2e branch
        required: false
        default: 'develop'
      runtime:
        required: false
        default: 'none'
        type: choice
        options:
          - none
          - docker
          - k8s
      reset:
        description: reset e2e
        required: false
        default: false
        type: boolean
concurrency:
  group: ${{ github.event.client_payload.stack || inputs.stack }}
  cancel-in-progress: true

jobs:
  debug:
    name: Debug output
    runs-on: ubuntu-22.04
    outputs:
      runtime: ${{ steps.runtime.outputs.runtime }}
      domain: ${{ steps.runtime.outputs.domain }}
    steps:
      - name: Print Entire Event Payload
        run: |
          echo "${{ toJson(github.event) }}"
      - uses: actions/checkout@v4
        with:
          repository: 'opencrvs/opencrvs-farajaland'
          fetch-depth: 0

      - name: Checkout country branch
        run: |
          git checkout ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}

      - name: Select docker swarm or k8s
        # Environment is selected based on stack hash with is always constant
        # Only first 8 symbols are used from hash and stack_id number is generated
        # - Odd numbers are deployed to docker swarm
        # - Even numbers are deployed to k8s
        # E/g ocrvs-9595 has stack id 2766917431, stack_id % 2 equals 1, which means docker
        id: runtime
        env:
          run_id: ${{ github.run_id }}
          runtime: ${{ github.event.client_payload.runtime || inputs.runtime }}
          stack: ${{ github.event.client_payload.stack || inputs.stack }}
        run: |
          stack_hash=$(echo -n "$stack" | sha256sum | head -c 8)
          stack_id=$((16#$stack_hash))
          if [[ -n "$runtime" && "$runtime" != "none" ]]; then
            runtime="$runtime"
          elif [[ ! -f infrastructure/.kube ]]; then
            echo "Repository is not compatible with kubernetes"
            runtime="docker"
          elif (( stack_id % 2 == 0 )); then
            runtime="k8s"
          else
            runtime="docker"
          fi
          if [[ "$runtime" == "docker" ]]; then
            domain=${{ github.event.client_payload.stack || inputs.stack }}.${{ vars.DOMAIN }}
          else
            domain=${{ github.event.client_payload.stack || inputs.stack }}.k8s-e2e.${{ vars.DOMAIN }}
          fi
          echo "domain=$domain" >> $GITHUB_OUTPUT
          echo "runtime=$runtime" >> $GITHUB_OUTPUT
          echo "domain=$domain"
          echo "runtime=$runtime"
  deploy-docker:
    needs: debug
    if: needs.debug.outputs.runtime == 'docker'
    uses: ./.github/workflows/deploy.yml
    with:
      core-image-tag: ${{ github.event.client_payload.core-image-tag || github.event.inputs.core-image-tag }}
      countryconfig-image-tag: ${{ github.event.client_payload.countryconfig-image-tag || github.event.inputs.countryconfig-image-tag }}
      stack: ${{ github.event.client_payload.stack || github.event.inputs.stack }}
      dependencies: false
      e2e_branch: ${{ github.event.client_payload.branch || github.event.inputs.branch }}
      reset: 'true'
    secrets: inherit
  deploy-k8s:
    if: needs.debug.outputs.runtime == 'k8s'
    needs: debug
    uses: ./.github/workflows/k8s-deploy.yml
    with:
      core-image-tag: ${{ github.event.client_payload.core-image-tag || inputs.core-image-tag }}
      countryconfig-image-tag: ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}
      environment: ${{ github.event.client_payload.stack || inputs.stack }}
      reset: ${{ github.event.client_payload.reset || inputs.reset || true }}
      keep-e2e: ${{ github.event.client_payload.keep-e2e == 'true' || github.event.client_payload.keep-e2e == true || inputs.keep-e2e || false }}
    secrets: inherit
  discover-tests:
    name: Discover test directories
    runs-on: ubuntu-24.04
    outputs:
      test_matrix: ${{ steps.list-tests.outputs.test_matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'opencrvs/opencrvs-farajaland'
          fetch-depth: 0

      - name: Checkout country branch
        run: |
          git checkout ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}

      - name: Set up Node.js from country .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: List Test Directories
        id: list-tests
        run: |
          tests_suites=$(cd e2e/testcases; find * -type f -name "*.spec.ts" | jq -R -s -c 'split("\n")[:-1]')
          echo "Test suites: $tests_suites"
          echo "test_matrix=$tests_suites" >> $GITHUB_OUTPUT
          echo "test_matrix=$tests_suites"
      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn/v6
            ~/.cache/ms-playwright
          key: ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: yarn
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npx playwright install --with-deps

  test:
    needs: [debug, deploy-docker, deploy-k8s, discover-tests]
    # Continue if at least one dependency succeeded (docker OR k8s ran)
    if: |
      always() && (
        needs.deploy-docker.result == 'success' ||
        needs.deploy-k8s.result == 'success'
      )
    runs-on: ubuntu-24.04
    environment: ${{ github.event.client_payload.stack || inputs.stack }}
    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.discover-tests.outputs.test_matrix) }}
    name: ${{ matrix.test_file }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'opencrvs/opencrvs-farajaland'
          fetch-depth: 0

      - name: Checkout country branch
        run: |
          git checkout ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}
      - name: Set up Node.js from country .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            node_modules
            ~/.cache/yarn/v6
            ~/.cache/ms-playwright
          key: ${{ github.event.client_payload.countryconfig-image-tag || inputs.countryconfig-image-tag }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn
      - uses: nick-fields/retry@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npx playwright install --with-deps
      - name: Run Playwright Tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 2
          command: |
            curl -s -o playwright.config.ts https://raw.githubusercontent.com/opencrvs/e2e/refs/heads/k8s-integration/playwright.config.ts;
            export NODE_EXTRA_CA_CERTS=/tmp/letsencrypt-stg-root-x1.pem
            curl -s -o $NODE_EXTRA_CA_CERTS https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem;
            npx playwright test ./e2e/testcases/${{ matrix.test_file }}
        env:
          DOMAIN: '${{ needs.debug.outputs.domain }}'
          # TODO: remove this variable on Jul 30 2025, check Farajaland latest fix
          IGNORE_CA: '1'
      - id: ctrf_check
        if: always()
        run: |
          [ -d ctrf ] && \
           echo "ctrf=true" >> $GITHUB_OUTPUT || \
           echo "ctrf=false" >> $GITHUB_OUTPUT
      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json
        if: always() && steps.ctrf_check.outputs.ctrf == 'true'

      - name: Form the artifact name from test_file
        if: always()
        id: artifact
        run: echo "artifact=$(echo '${{ matrix.test_file }}' | sed 's/\//__/g')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ github.event.client_payload.stack || inputs.stack }}-${{ steps.artifact.outputs.artifact }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: playwright-report/
          retention-days: 30

  get-previous-run:
    runs-on: ubuntu-latest
    outputs:
      previous_run_result: ${{ steps.set-output.outputs.result }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous Run Conclusion
        id: get-previous-conclusion
        run: |
          previous_conclusion=$(gh run list --limit 1 --status=completed --workflow="Deploy & run E2E" --json conclusion -q '.[0].conclusion')
          echo "PREVIOUS_CONCLUSION=$previous_conclusion" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Set Output Based on Conclusion
        id: set-output
        run: |
          echo "result=$PREVIOUS_CONCLUSION" >> $GITHUB_OUTPUT

  cleanup-stack-docker:
    needs: [test, debug]
    runs-on: ubuntu-24.04
    if: always() && needs.debug.outputs.keep_e2e == 'false' && needs.debug.outputs.runtime == 'docker' && needs.test.result == 'success'
    env:
      stack: ${{ github.event.client_payload.stack || inputs.stack }}
      keep_e2e: ${{ github.event.client_payload.keep-e2e || inputs.keep-e2e }}
    steps:
      - uses: actions/checkout@v4
      - name: Read known hosts
        run: |
          echo "KNOWN_HOSTS<<EOF" >> $GITHUB_ENV
          sed -i -e '$a\' ./infrastructure/known-hosts
          cat ./infrastructure/known-hosts >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ env.KNOWN_HOSTS }}

      - name: Unset KNOWN_HOSTS variable
        run: |
          echo "KNOWN_HOSTS=" >> $GITHUB_ENV
      - name: Cleanup e2e stack
        run: |
          bash infrastructure/deployment/cleanup-e2e-stack.sh \
          --stack=${stack} \
          --ssh_host=${{ vars.SSH_HOST || secrets.SSH_HOST }} \
          --ssh_port=${{ vars.SSH_PORT || secrets.SSH_PORT }} \
          --ssh_user=${{ secrets.SSH_USER }}

  cleanup-stack-k8s:
    needs: [test, debug]
    runs-on: [self-hosted]
    env:
      ENV: ${{ github.event.client_payload.stack || inputs.stack }}
    if: always() && needs.debug.outputs.keep_e2e == 'false' && needs.debug.outputs.runtime == 'k8s' && needs.test.result == 'success'
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        - name: Update k8s-env/opencrvs/values.yaml
          run: |
            sed -i -e "s#{{STACK}}#${ENV}#g" k8s-env/opencrvs/values.yaml
        - name: Cleanup environment
          run: |
            kubectl delete job -n opencrvs-${ENV} --ignore-not-found=true data-cleanup
            helm template -f k8s-env/opencrvs/values.yaml \
                --set data_cleanup.enabled=true \
                --set image.tag="$CORE_IMAGE_TAG" \
                --namespace opencrvs-${ENV} \
                -s templates/data-cleanup-job.yaml \
                oci://ghcr.io/opencrvs/opencrvs-services | kubectl apply -n opencrvs-${ENV} --wait=true -f -
            sleep 30;
            kubectl logs job/data-cleanup -f --all-containers=true -n opencrvs-${ENV} || true
            kubectl wait --for=condition=complete job/data-cleanup -n opencrvs-${ENV} --timeout=600s;
        - name: Delete helm release and namespace
          run: |
            kubectl delete namespace opencrvs-${ENV}
