name: Deploy (k8s)
run-name: 'Deploy OpenCRVS on k8s (core: ${{ inputs.core-image-tag }}, country: ${{ inputs.countryconfig-image-tag }})'
on:
  workflow_call:
    inputs:
      core-image-tag:
        type: string
      countryconfig-image-tag:
        type: string
      environment:
        type: string
      reset:
        type: boolean
      keep-e2e:
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      core-image-tag:
        description: 'Tag of the core image'
        required: true
        default: 'develop'
      countryconfig-image-tag:
        description: 'Tag of the countryconfig image'
        required: true
        default: 'develop'
      environment:
        description: 'Target environment'
        required: true
        default: 'demo'
        type: string
      reset:
        description: 'Reset environment after deploy'
        required: false
        default: false
        type: boolean
      keep-e2e:
        description: 'Add keep_namespace label'
        required: false
        type: boolean
        default: false
jobs:
  deploy:
    env:
      ENV: ${{ inputs.environment }}
      CORE_IMAGE_TAG: ${{ inputs.core-image-tag }}
      COUNTRYCONFIG_IMAGE_TAG: ${{ inputs.countryconfig-image-tag }}
    runs-on: [self-hosted]
    steps:
      # FYI: Repository is needed only due to single file: examples/dev/opencrvs-services/values.yaml
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate summary
        run: |
          echo "Deploying environment to https://${{ inputs.environment }}.k8s-e2e.${{ vars.DOMAIN }}" >> $GITHUB_STEP_SUMMARY
          echo "Core image tag: ${{ inputs.core-image-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Country config image tag: ${{ inputs.countryconfig-image-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "Reset environment: ${{ inputs.reset }}" >> $GITHUB_STEP_SUMMARY
      - name: Print deployment parameters
        run: |
          echo "Environment: $ENV"
          echo "Core Image: $CORE_IMAGE_TAG"
          echo "Country Config Image: $COUNTRYCONFIG_IMAGE_TAG"
        # Create namespace separately from deployments. With two separate deployments (mosip & e2e), if other fails, we still want to be able to clean it based on updated_at.
      - name: Ensure namespace exists with updated_at label
        run: |
          if ! kubectl get namespace "opencrvs-${ENV}" >/dev/null 2>&1; then
            kubectl create namespace "opencrvs-${ENV}"
          fi
          kubectl label namespace --overwrite "opencrvs-${ENV}" updated_at=$(date +%s)
      - name: Deploy OpenCRVS MOSIP API
        run: |
          helm upgrade --install mosip-api oci://ghcr.io/opencrvs/opencrvs-mosip \
          --namespace "opencrvs-${ENV}" \
          -f k8s-env/mosip-api/values.yaml \
          --set hostname=$ENV.k8s-e2e.opencrvs.dev \
          --atomic
      - name: Add updated_at timestamp label to namespace
        run: kubectl label namespace --overwrite opencrvs-${ENV} updated_at=$(date +%s)
      - name: Copy secrets from dependencies into application namespace
        run: |
          secrets=(
            "elasticsearch-admin-user"
            "redis-opencrvs-users"
            "minio-opencrvs-users"
            "mongodb-admin-user"
            "postgres-admin-user"
          )
          for secret in "${secrets[@]}"; do
            kubectl get secret $secret -n opencrvs-deps-e2e -o yaml \
            | sed "s#namespace: opencrvs-deps-e2e#namespace: opencrvs-${ENV}#" \
            | grep -vE 'resourceVersion|uid|creationTimestamp' \
            | kubectl apply -n opencrvs-${ENV} -f - \
            || echo "Secret $secret doesn't exist in opencrvs-deps-e2e namespace"
          done
      - name: Update k8s-env/opencrvs/values.yaml
        run: |
          sed -i -e "s#{{STACK}}#${ENV}#g" k8s-env/opencrvs/values.yaml
      - name: "FIXME: temporary remove data-migration job due to issues"
        run: |
          kubectl delete job -n "opencrvs-${ENV}" --ignore-not-found=true data-migration || true
      - name: Deploy with Helm
        run: |
          helm upgrade --install opencrvs oci://ghcr.io/opencrvs/opencrvs-services \
            --timeout 15m \
            --namespace "opencrvs-${ENV}" \
            -f k8s-env/opencrvs/values.yaml \
            --atomic \
            --set image.tag="$CORE_IMAGE_TAG" \
            --set countryconfig.image.tag="$COUNTRYCONFIG_IMAGE_TAG" \
            --set hostname=$ENV.k8s-e2e.opencrvs.dev \
            --set environment="$ENV"
      - name: Add keep namespace label opencrvs-${ENV}
        if: inputs.keep-e2e
        run: kubectl label namespace opencrvs-${ENV} keep_namespace='true' --overwrite
      - name: Cleanup Helm Locks
        if: failure() || cancelled()
        run: |
          kubectl -n "opencrvs-${ENV}" get secrets -l owner=helm -o json | \
          jq -r '.items[] | select(.metadata.labels.status=="pending-install" or .metadata.labels.status=="pending-upgrade" or .metadata.labels.status=="pending-rollback") | .metadata.name' | \
          xargs -r kubectl -n "opencrvs-${ENV}" delete secret || \
          echo "No helm locks found, all is good"

  reset-data:
    if: ${{ inputs.reset }}
    needs: deploy
    uses: ./.github/workflows/k8s-reset-data.yml
    with:
      namespace: 'opencrvs-${{ inputs.environment }}'
      environment: ${{ inputs.environment }}
    secrets: inherit
