name: Seed data
run-name: Seed data to ${{ inputs.environment }} core=${{ inputs.core-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      core-image-tag:
        required: true
        type: string
      stack:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'qa'
        options:
          - qa
      core-image-tag:
        description: Core DockerHub image tag
      stack:
        required: true
        description: Stack name
        type: string
jobs:
  seed-data:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    outputs:
      outcome: ${{ steps.seed.outcome }}
    timeout-minutes: 60
    steps:
       - name: Pull the seed-data image
         run: docker pull ghcr.io/opencrvs/ocrvs-data-seeder:${{ inputs.core-image-tag }}

       - name: Run docker container
         id: seed
         run: |
           docker run \
             -e ACTIVATE_USERS=${{ vars.ACTIVATE_USERS }} \
             -e GATEWAY_HOST="https://gateway.${{inputs.stack}}.opencrvs.dev" \
             -e AUTH_HOST="https://auth.${{inputs.stack}}.opencrvs.dev" \
             -e COUNTRY_CONFIG_HOST="https://countryconfig.${{inputs.stack}}.opencrvs.dev" \
             -e SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }} \
             ghcr.io/opencrvs/ocrvs-data-seeder:${{ inputs.core-image-tag }}
