name: Seed data
run-name: Seed data to ${{ inputs.environment }} core=${{ inputs.core-image-tag }}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      core-image-tag:
        required: true
        type: string
      stack:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to seed data
        required: true
        default: 'qa'
        options:
          - qa
      core-image-tag:
        description: Core DockerHub image tag
      stack:
        required: true
        description: Stack name
        type: string
jobs:
  seed-data:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    outputs:
      outcome: ${{ steps.seed.outcome }}
    timeout-minutes: 60
    steps:
      - name: Clone core
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'opencrvs/opencrvs-core'
          path: './opencrvs-core'

      - name: Set CORE_VERSION from inputs
        if: ${{ inputs.core-image-tag }}
        run: |
          cd opencrvs-core
          git checkout ${{ inputs.core-image-tag }}

      # copy ./opencrvs-core/packages/data-seeder to a new temporary directory
      - name: Copy data-seeder
        run: |
          cp -r ./opencrvs-core/packages/data-seeder ./data-seeder

      - name: Install dependencies
        working-directory: ./data-seeder
        run: yarn install

      - name: Seed data on given environment
        uses: nick-fields/retry@v2
        id: seed
        with:
          timeout_minutes: 10
          max_attempts: 5
          command: |
            cd ./data-seeder
            NODE_OPTIONS=--dns-result-order=ipv4first npx ts-node --transpile-only -r tsconfig-paths/register src/index.ts
        env:
          ACTIVATE_USERS: ${{ vars.ACTIVATE_USERS }}
          GATEWAY_HOST: 'https://gateway.${{inputs.stack}}.opencrvs.dev'
          AUTH_HOST: 'https://auth.${{inputs.stack}}.opencrvs.dev'
          COUNTRY_CONFIG_HOST: 'https://countryconfig.${{inputs.stack}}.opencrvs.dev'
          SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
